### PR TITLE
#2: sentry handler can now decide if it will ignore @ operator or not

### PR DESCRIPTION
**Pull request by brunovianarezende**
right now the behaviour is to always ignore the @ (error control)
operator, this change allows the user of the extension to decided if it
will be the case in his installation or not. The default will be to
ignore the @ operator and always log errors to sentry.

### CODE REVIEW

**Comment by wo0dyn** [comment]
Thank you very much for the PR Bruno. I'll try to check this out very soon. :wink:

**Comment by brunovianarezende** [comment]
cool! I hope you get some time :-)

**Comment by brunovianarezende** [comment]
any news on this?

**Comment by wo0dyn** [comment]
Sorry, I was not really working on a Magento project last months. I'll try to test that asap. Really.

**Pull request merged**
